first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from navigation import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('navigation/', include('navigation.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

navigation/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('register/',views.register,name='register'), 
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

navigation/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'
    def __str__(self): 
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    def __str__(self):
        return self.title


class UserProfile(models.Model):
    # 这一行是必须的
    # 建立与 User 模型之间的一对一关系
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    # 想增加的属性
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    
    def __str__(self):
        return self.user.username

navigation/forms.py
from django import forms
from django.contrib.auth.models import User
from navigation.models import UserProfile 

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

navigation/views.py
from django.http import HttpResponse
from django.shortcuts import render
from navigation.models import Category
from navigation.models import Page
from navigation.forms import UserForm, UserProfileForm
from django.shortcuts import redirect, reverse
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from datetime import datetime

def index(request):
    # 查询数据库，获取目前存储的所有分类
    # 按点赞次数倒序排列分类
    # 获取前 5 个分类（如果分类数少于 5 个，那就获取全部）
    # 把分类列表放入 context_dict 字典
    # 稍后传给模板引擎
    category_list = Category.objects.order_by('-likes')[:5]
    context_dict = {'categories': category_list}
    # 渲染响应，发给客户端
    page_list = Page.objects.order_by('-views')[:5]
    context_dict["pages"] = page_list
    response = render(request, 'navigation/index.html', context_dict)
    # 调用处理 cookie 的辅助函数
    visitor_cookie_handler(request, response)
    # 返回 response 对象，更新目标 cookie
    return response

def about(request):
    #return HttpResponse("龙腾测试！！！ <a href='/navigation/'>首页</a>")
    return render(request, 'navigation/about.html')


def show_category(request, category_name_slug):
    # 创建上下文字典，稍后传给模板渲染引擎
    context_dict = {}
    try:
        # 能通过传入的分类别名找到对应的分类吗？
        # 如果找不到， .get() 方法抛出 DoesNotExist 异常
        # 因此 .get() 方法返回一个模型实例或抛出异常
        category = Category.objects.get(slug=category_name_slug)
        # 检索关联的所有网页
        # 注意， filter() 返回一个网页对象列表或空列表
        pages = Page.objects.filter(category=category)
        # 把得到的列表赋值给模板上下文中名为 pages 的键
        context_dict['pages'] = pages
        # 也把从数据库中获取的 category 对象添加到上下文字典中
        # 我们将在模板中通过这个变量确认分类是否存在
        context_dict['category'] = category
    except Category.DoesNotExist:
        # 没找到指定的分类时执行这里
        # 什么也不做
        # 模板会显示消息，指明分类不存在
        context_dict['category'] = None
        context_dict['pages'] = None
    # 渲染响应，返回给客户端
    return render(request, 'navigation/category.html', context_dict)


def register(request):
    # 一个布尔值，告诉模板注册是否成功
    # 一开始设为 False，注册成功后改为 True
    registered = False
    # 如果是 HTTP POST 请求，处理表单数据
    if request.method == 'POST':
        # 尝试获取原始表单数据
        # 注意， UserForm 和 UserProfileForm 中的数据都需要
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        # 如果两个表单中的数据是有效的……
        if user_form.is_valid() and profile_form.is_valid():
            # 把 UserForm 中的数据存入数据库
            user = user_form.save()
            # 使用 set_password 方法计算密码哈希值
            # 然后更新 user 对象
            user.set_password(user.password)
            user.save()
            # 现在处理 UserProfile 实例
            # 因为要自行处理 user 属性，所以设定 commit=False
            # 延迟保存模型，以防出现完整性问题
            profile = profile_form.save(commit=False)
            profile.user = user
            # 用户提供头像了吗？
            # 如果提供了，从表单数据库中提取出来，赋给 UserProfile 模型
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
                # 保存 UserProfile 模型实例
            profile.save()
            # 更新变量的值，告诉模板成功注册了
            registered = True
        else:
            # 表单数据无效，出错了
            # 在终端打印问题
            print(user_form.errors, profile_form.errors)
    else:
        # 不是 HTTP POST 请求，渲染两个 ModelForm 实例
        # 表单为空，待用户填写
        user_form = UserForm()
        profile_form = UserProfileForm()
    # 根据上下文渲染模板
    return render(request,
                  'navigation/register.html',
                  {'user_form': user_form,
                  'profile_form': profile_form,
                  'registered': registered})


def user_login(request):
    # 如果是 HTTP POST 请求，尝试提取相关信息
    if request.method == 'POST':
        # 获取用户在登录表单中输入的用户名和密码
        # 我们使用的是 request.POST.get('<variable>')
        # 而不是 request.POST['<variable>']
        # 这是因为对应的值不存在时，前者返回 None，
        # 而后者抛出 KeyError 异常
        username = request.POST.get('username')
        password = request.POST.get('password')
        # 使用 Django 提供的函数检查 username/password 是否有效
        # 如果有效，返回一个 User 对象
        user = authenticate(username=username, password=password)
        # 如果得到了 User 对象，说明用户输入的凭据是对的
        # 如果是 None（ Python 表示没有值的方式），说明没找到与凭据匹配的用户
        if user:
        # 账户激活了吗？可能被禁了
            if user.is_active:
                # 登入有效且已激活的账户
                # 然后重定向到首页
                login(request, user)
                return redirect(reverse('index'))
            else:
                # 账户未激活，禁止登录
                return HttpResponse("Your Rango account is disabled.")
        else:
            # 提供的登录凭据有问题，不能登录
            print("Invalid login details: {0}, {1}".format(username, password))
            return HttpResponse("Invalid login details supplied.")
    # 不是 HTTP POST 请求，显示登录表单
    # 极有可能是 HTTP GET 请求
    else:
        # 没什么上下文变量要传给模板系统
        # 因此传入一个空字典
        return render(request, 'navigation/login.html', {})


@login_required
def user_logout(request):
    # 可以确定用户已登录，因此直接退出
    logout(request)
    # 把用户带回首页
    return redirect(reverse('index'))



def visitor_cookie_handler(request, response):
    # 获取网站的访问次数
    # 使用 COOKIES.get() 函数读取“visits”cookie
    # 如果目标 cookie 存在，把值转换为整数
    # 如果目标 cookie 不存在，返回默认值 1
    visits = int(request.COOKIES.get('visits', '1'))
    last_visit_cookie = request.COOKIES.get('last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],'%Y-%m-%d %H:%M:%S')
    # 如果距上次访问已超过1s……
    if (datetime.now() - last_visit_time).seconds > 0:
        visits = visits + 1
        # 增加访问次数后更新“last_visit”cookie
        response.set_cookie('last_visit', str(datetime.now()))
    else:
        # 设定“last_visit”cookie
        response.set_cookie('last_visit', last_visit_cookie)
        # 更新或设定“visits”cookie
    response.set_cookie('visits', visits)

templates/navigation/about.html
{% extends 'navigation/base.html' %}
{% load staticfiles %} 
{% block title_block %}
关于
{% endblock %}
{% block body_block %}
    <h1>我们在一起了</h1>
    
    <div>
      <a href="/navigation/">首页</a><br />
      <img src="{% static "images/django.png" %}"
           alt="Picture of django" /> 
       <img src="/media/cat.jpg"
           alt="Picture of cat" />
    </div>
{% endblock  %}

templates/navigation/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load navigation_template_tags %}
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width,
initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="{% static 'images/favicon.ico' %}">
<title>
Navigation - {% block title_block %}title{% endblock %}
</title>
<!-- Bootstrap core CSS -->
<link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
<button class="navbar-toggler navbar-toggler-right hidden-lg-up"
type="button"
data-toggle="collapse"
data-target="#navbar"
aria-controls="navbar"
aria-expanded="false"
aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
<a class="navbar-brand" href="{% url 'index' %}">Navigation</a>
<div class="collapse navbar-collapse" id="navbar">
<ul class="navbar-nav mr-auto">
<li class="nav-item active">
<a class="nav-link" href="{% url 'index' %}">
首页
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="{% url 'about' %}">
关于
</a>
</li>
{% if user.is_authenticated %}
<li class="nav-item">
<a class="nav-link" href="{% url 'logout' %}?next=/rango/">
退出
</a>
</li>
{% else %}
<li class="nav-item">
<a class="nav-link" href="{% url 'register' %}">
注册
</a>
</li>
<li class="nav-item">
<a class="nav-link" href="{% url 'login' %}">
登录
</a>
</li>
{% endif %}
</ul>
</div>
</nav>
<div class="container-fluid">
<div class="row">
<div class="col-sm-3 col-md-2 sidebar">
{% block sidebar_block %}
{% get_category_list category %}
{% endblock %}
</div>
<div class="col-md-10 offset-md-2">
{% block body_block %}{% endblock %}
</div>
</div>
</div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js">
</script>
<srript src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js">
</script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js">
</script>
</body>
</html

templates/navigation/category.html
{% extends 'navigation/base.html' %}
{% block title_block %}
分类
{% endblock %}
{% load staticfiles %}
{% block body_block %}
    <div>
    {% if category %}
      <h1>{{ category.name }}</h1>
      {% if pages %}
        <ul>
          {% for page in pages %}
            <li><a href="{{ page.url }}">{{ page.title }}</a></li>
          {% endfor %}
        </ul>
      {% else %}
         <strong>当前分类没有内容.</strong>
      {% endif %}
    {% else %}
      指定分类不存在
    {% endif %}
    </div>
    <div>
      <a href="{% url 'index' %}">首页</a><br />
    </div>
{% endblock  %}

templates/navigation/cats.html
<ul>
{% if cats %}
    {% for c in cats %}
        {% if c == act_cat %}
        <li><strong><a href="{% url 'show_category' c.slug %}">{{ c.name }}</a></strong></li>
        {% else %}
        <li><a href="{% url 'show_category' c.slug %}">{{ c.name }}</a></li>
        {% endif %}
    {% endfor %}
{% else %}
    <li><strong>There are no categories present.</strong></li>
{% endif %}
</ul>

templates/navigation/index.html
{% extends 'navigation/base.html' %}
{% load staticfiles %}
{% block title_block %}
首页
{% endblock %}
{% block body_block %}
<div class="jumbotron">
<h1 class="display-3">欢迎</h1>
{% if user.is_authenticated %}
<h1>{{ user.username }}!</h1>
{% else %}
<h1>游客 </h1>
{% endif %}
</div>
<div class="row marketing">
<div class="col-lg-6">
<h4>最受欢迎的类别</h4>
<p>
{% if categories %}
<ul>
{% for category in categories %}
<li><a href="{% url 'show_category' category.slug %}">
{{ category.name }}</a></li>
{% endfor %}
</ul>
{% else %}
<strong>There are no categories present.</strong>
{% endif %}
</p>
</div>
<div class="col-lg-6">
<h4>浏览最多的页面</h4>
<p>
{% if pages %}
<ul>
{% for page in pages %}
<li><a href="{{ page.url }}">{{ page.title }}</a></li>
{% endfor %}
</ul>
{% else %}
<strong>There are no categories present.</strong>
{% endif %}
</p>
</div>
</div>
<img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" />
{% endblock %}

templates/navigation/login.html
{% extends 'navigation/base.html' %}
{% block title_block %}
登录
{% endblock %}
{% block body_block %}
<link href="http://v4-alpha.getbootstrap.com/examples/signin/signin.css"
rel="stylesheet">
<div class="jumbotron">
<h1 class="display-3"> </h1>
</div>
<form class="form-signin" role="form" method="post" action="{% url 'login' %}">
{% csrf_token %}

<label for="id_username" class="sr-only">用户名</label>
<input type="text" name="username" id="id_username" class="form-control"
placeholder="用户名" required autofocus>
<label for="id_password" class="sr-only">密码</label>
<input type="password" name="password" id="id_password" class="form-control"
placeholder="密码" required>
<button class="btn btn-lg btn-primary btn-block" type="submit"
value="Submit" />登录</button>
</form>


{% endblock %}

templates/navigation/register.html
{% extends "navigation/base.html" %}
{% block title_block %}
注册
{% endblock %}
{% block body_block %}
<h1></h1>
{% if registered %}
<strong>感谢注册</strong>
<a href="{% url 'index' %}">返回首页</a><br />
{% else %}
<form  method="post" action="{% url 'register' %}" enctype="multipart/form-data">
{% csrf_token %}
<div class="form-group row">
    <label class="col-md-1  offset-md-1" for="id_username">用户名:</label>
    <div class="col-md-3">
        <input class="form-control" id="id_username" maxlength="30" name="username" type="text" />
    </div>
</div>
<div class="form-group row">
    <label class="col-md-1 offset-md-1" for="id_email">邮箱:</label>
    <div class="col-md-3">
        <input class="form-control" id="id_email" name="email" type="email" />
    </div>
</div>
<div class="form-group row">
    <label class="col-md-1 offset-md-1" for="id_password">密码:</label>
    <div class="col-md-3">
        <input class="form-control" id="id_password" name="password" type="password" />
    </div>
</div>
<div class="form-group row">
    <label class="col-md-1 offset-md-1" for="id_website">个人站点:</label>
    <div class="col-md-3">
        <input class="form-control" id="id_website" name="website" type="text" />
    </div>
</div>
<div class="form-group row">
    <label class="col-md-1 offset-md-1" for="id_picture">头像:</label>
    <div class="col-md-3">
        <input class="form-control" id="id_picture" name="picture" type="file" />
    </div>
</div>
<button type="submit" class="btn btn-primary offset-md-1">提交</button>
</form>
</div>
{% endif %}
{% endblock %}